spring:
  application:
    name: todo-service
  datasource:
    url: ${TODO_DB_URL:jdbc:h2:mem:todo;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${TODO_DB_USER:sa}
    password: ${TODO_DB_PASS:}
  sql:
    init:
      mode: always
      encoding: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${TODO_SERVER_PORT:8080}
logging:
  level:
    com.ty.todo: INFO
