spring:
  application:
    name: todo-service
  datasource:
    url: ${TODO_DB_URL:jdbc:h2:mem:todo;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${TODO_DB_USER:sa}
    password: ${TODO_DB_PASS:}
  sql:
    init:
      mode: always
      encoding: UTF-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${TODO_SERVER_PORT:8080}
logging:
  level:
    com.ty.todo: INFO
todo:
  reminder:
    poll-interval: ${TODO_REMINDER_POLL_INTERVAL:PT30S}
    mail:
      enabled: ${TODO_MAIL_ENABLED:false}
      from: ${TODO_MAIL_FROM:no-reply@todo.local}
      subject: ${TODO_MAIL_SUBJECT:Todo Reminder}
