spring:
  application:
    name: todo-service
  config:
    import: optional:file:./todo-config.yml
  datasource:
    url: ${todo.db.url:jdbc:mysql://localhost:3306/todo_cli}
    username: ${todo.db.user:root}
    password: ${todo.db.password:password}
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${todo.server.port:8080}
logging:
  level:
    com.ty.todo: debug
todo:
  reminder:
    poll-interval: ${todo.reminder.poll.interval:PT30S}
    mail:
      enabled: ${todo.mail.enabled:false}
      from: ${todo.mail.from:no-reply@todo.local}
      subject: ${todo.mail.subject:Todo Reminder}
